"""baseline_schema

Revision ID: 2eb38d78af14
Revises: 
Create Date: 2026-03-25 20:28:48.101071

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2eb38d78af14'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('empresas',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('nombre', sa.String(), nullable=True),
    sa.Column('rnc', sa.String(), nullable=True),
    sa.Column('direccion', sa.String(), nullable=True),
    sa.Column('telefono', sa.String(), nullable=True),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('secuencia_ncf', sa.Integer(), nullable=True),
    sa.Column('secuencia_ecf', sa.Integer(), nullable=True),
    sa.Column('itbis', sa.Float(), nullable=True),
    sa.Column('regimen', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('rnc')
    )
    op.create_table('clientes',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('empresa_id', sa.String(), nullable=True),
    sa.Column('rnc', sa.String(), nullable=True),
    sa.Column('nombre', sa.String(), nullable=True),
    sa.Column('nombre_comercial', sa.String(), nullable=True),
    sa.Column('tipo', sa.Enum('PERSONA_FISICA', 'PERSONA_JURIDICA', 'REGIMEN_ESPECIAL', name='tipocontribuyente'), nullable=True),
    sa.Column('estatus', sa.String(), nullable=True),
    sa.Column('regimen_pago', sa.String(), nullable=True),
    sa.Column('direccion', sa.String(), nullable=True),
    sa.Column('telefono', sa.String(), nullable=True),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('limite_credito', sa.Float(), nullable=True),
    sa.Column('saldo_pendiente', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['empresa_id'], ['empresas.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('plantillas_factura',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('empresa_id', sa.String(), nullable=True),
    sa.Column('nombre', sa.String(), nullable=True),
    sa.Column('logo_url', sa.Text(), nullable=True),
    sa.Column('color_primario', sa.String(), nullable=True),
    sa.Column('color_secundario', sa.String(), nullable=True),
    sa.Column('color_texto', sa.String(), nullable=True),
    sa.Column('color_fondo', sa.String(), nullable=True),
    sa.Column('mostrar_logo', sa.Boolean(), nullable=True),
    sa.Column('mostrar_datos_empresa', sa.Boolean(), nullable=True),
    sa.Column('mostrar_ncf', sa.Boolean(), nullable=True),
    sa.Column('mostrar_fecha', sa.Boolean(), nullable=True),
    sa.Column('mostrar_cliente', sa.Boolean(), nullable=True),
    sa.Column('mostrar_nota', sa.Boolean(), nullable=True),
    sa.Column('mostrar_qr', sa.Boolean(), nullable=True),
    sa.Column('mostrar_pie', sa.Boolean(), nullable=True),
    sa.Column('orden_secciones', sa.Text(), nullable=True),
    sa.Column('texto_encabezado', sa.Text(), nullable=True),
    sa.Column('texto_pie', sa.Text(), nullable=True),
    sa.Column('mensaje_adicional', sa.Text(), nullable=True),
    sa.Column('fuente_principal', sa.String(), nullable=True),
    sa.Column('tamaño_fuente', sa.Integer(), nullable=True),
    sa.Column('diseno_json', sa.Text(), nullable=True),
    sa.Column('es_predeterminada', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['empresa_id'], ['empresas.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('productos',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('empresa_id', sa.String(), nullable=True),
    sa.Column('codigo', sa.String(), nullable=True),
    sa.Column('nombre', sa.String(), nullable=True),
    sa.Column('descripcion', sa.String(), nullable=True),
    sa.Column('precio_unitario', sa.Float(), nullable=True),
    sa.Column('costo_unitario', sa.Float(), nullable=True),
    sa.Column('stock', sa.Float(), nullable=True),
    sa.Column('stock_minimo', sa.Float(), nullable=True),
    sa.Column('codigo_barra', sa.String(), nullable=True),
    sa.Column('aplica_itbis', sa.Boolean(), nullable=True),
    sa.Column('tipo_itbis', sa.Enum('ITBIS_0', 'ITBIS_18', 'ITBIS_EXENTO', 'ITBIS_REDUCIDO_13', name='tipoitbis'), nullable=True),
    sa.Column('activo', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['empresa_id'], ['empresas.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('proveedores',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('empresa_id', sa.String(), nullable=True),
    sa.Column('rnc', sa.String(), nullable=True),
    sa.Column('nombre', sa.String(), nullable=True),
    sa.Column('nombre_comercial', sa.String(), nullable=True),
    sa.Column('direccion', sa.String(), nullable=True),
    sa.Column('telefono', sa.String(), nullable=True),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['empresa_id'], ['empresas.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('usuarios',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('password', sa.String(), nullable=True),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('role', sa.Enum('ADMIN', 'CONTADOR', 'VENDEDOR', name='role'), nullable=True),
    sa.Column('empresa_id', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['empresa_id'], ['empresas.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_usuarios_email'), 'usuarios', ['email'], unique=True)
    op.create_table('cotizaciones',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('empresa_id', sa.String(), nullable=True),
    sa.Column('cliente_id', sa.String(), nullable=True),
    sa.Column('numero', sa.String(), nullable=True),
    sa.Column('secuencia', sa.Integer(), nullable=True),
    sa.Column('fecha', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('fecha_validez', sa.DateTime(), nullable=True),
    sa.Column('subtotal', sa.Float(), nullable=True),
    sa.Column('descuento', sa.Float(), nullable=True),
    sa.Column('itbis', sa.Float(), nullable=True),
    sa.Column('total', sa.Float(), nullable=True),
    sa.Column('estado', sa.Enum('PENDIENTE', 'ACEPTADA', 'RECHAZADA', 'VENCIDA', 'CONVERTIDA', name='estadocotizacion'), nullable=True),
    sa.Column('nota', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['cliente_id'], ['clientes.id'], ),
    sa.ForeignKeyConstraint(['empresa_id'], ['empresas.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('facturas',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('empresa_id', sa.String(), nullable=True),
    sa.Column('cliente_id', sa.String(), nullable=True),
    sa.Column('ncf', sa.String(), nullable=True),
    sa.Column('tipo_ncf', sa.Enum('B01', 'B02', 'B04', 'B11', 'B12', 'E31', 'E41', 'E43', 'E44', name='tiponcf'), nullable=True),
    sa.Column('secuencia', sa.Integer(), nullable=True),
    sa.Column('fecha', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('subtotal', sa.Float(), nullable=True),
    sa.Column('descuento', sa.Float(), nullable=True),
    sa.Column('itbis', sa.Float(), nullable=True),
    sa.Column('total', sa.Float(), nullable=True),
    sa.Column('estado', sa.Enum('PENDIENTE', 'PAGADA', 'VENCIDA', 'ANULADA', 'ENVIADA_DGII', name='estadofactura'), nullable=True),
    sa.Column('nota', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['cliente_id'], ['clientes.id'], ),
    sa.ForeignKeyConstraint(['empresa_id'], ['empresas.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('ncf')
    )
    op.create_table('kardex',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('producto_id', sa.String(), nullable=True),
    sa.Column('tipo', sa.String(), nullable=True),
    sa.Column('cantidad', sa.Float(), nullable=True),
    sa.Column('saldo_actual', sa.Float(), nullable=True),
    sa.Column('referencia', sa.String(), nullable=True),
    sa.Column('nota', sa.String(), nullable=True),
    sa.Column('fecha', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['producto_id'], ['productos.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('detalles_cotizacion',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('cotizacion_id', sa.String(), nullable=True),
    sa.Column('producto_id', sa.String(), nullable=True),
    sa.Column('descripcion', sa.String(), nullable=True),
    sa.Column('cantidad', sa.Float(), nullable=True),
    sa.Column('precio_unitario', sa.Float(), nullable=True),
    sa.Column('descuento', sa.Float(), nullable=True),
    sa.Column('itbis', sa.Float(), nullable=True),
    sa.Column('total', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['cotizacion_id'], ['cotizaciones.id'], ),
    sa.ForeignKeyConstraint(['producto_id'], ['productos.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('detalles_factura',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('factura_id', sa.String(), nullable=True),
    sa.Column('producto_id', sa.String(), nullable=True),
    sa.Column('descripcion', sa.String(), nullable=True),
    sa.Column('cantidad', sa.Float(), nullable=True),
    sa.Column('precio_unitario', sa.Float(), nullable=True),
    sa.Column('descuento', sa.Float(), nullable=True),
    sa.Column('itbis', sa.Float(), nullable=True),
    sa.Column('total', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['factura_id'], ['facturas.id'], ),
    sa.ForeignKeyConstraint(['producto_id'], ['productos.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('notas_credito',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('empresa_id', sa.String(), nullable=True),
    sa.Column('cliente_id', sa.String(), nullable=True),
    sa.Column('factura_id', sa.String(), nullable=True),
    sa.Column('ncf', sa.String(), nullable=True),
    sa.Column('secuencia', sa.Integer(), nullable=True),
    sa.Column('ncf_original', sa.String(), nullable=True),
    sa.Column('fecha', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('subtotal', sa.Float(), nullable=True),
    sa.Column('itbis', sa.Float(), nullable=True),
    sa.Column('total', sa.Float(), nullable=True),
    sa.Column('motivo', sa.String(), nullable=True),
    sa.Column('estado', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['cliente_id'], ['clientes.id'], ),
    sa.ForeignKeyConstraint(['empresa_id'], ['empresas.id'], ),
    sa.ForeignKeyConstraint(['factura_id'], ['facturas.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('ncf')
    )
    op.create_table('notas_debito',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('empresa_id', sa.String(), nullable=True),
    sa.Column('cliente_id', sa.String(), nullable=True),
    sa.Column('factura_id', sa.String(), nullable=True),
    sa.Column('ncf', sa.String(), nullable=True),
    sa.Column('secuencia', sa.Integer(), nullable=True),
    sa.Column('ncf_original', sa.String(), nullable=True),
    sa.Column('fecha', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('subtotal', sa.Float(), nullable=True),
    sa.Column('itbis', sa.Float(), nullable=True),
    sa.Column('total', sa.Float(), nullable=True),
    sa.Column('motivo', sa.String(), nullable=True),
    sa.Column('estado', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['cliente_id'], ['clientes.id'], ),
    sa.ForeignKeyConstraint(['empresa_id'], ['empresas.id'], ),
    sa.ForeignKeyConstraint(['factura_id'], ['facturas.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('ncf')
    )
    op.create_table('pagos',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('empresa_id', sa.String(), nullable=True),
    sa.Column('factura_id', sa.String(), nullable=True),
    sa.Column('monto', sa.Float(), nullable=True),
    sa.Column('metodo', sa.Enum('EFECTIVO', 'TRANSFERENCIA', 'CHEQUE', 'TARJETA', 'OTRO', name='metodopago'), nullable=True),
    sa.Column('referencia', sa.String(), nullable=True),
    sa.Column('nota', sa.Text(), nullable=True),
    sa.Column('fecha', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['empresa_id'], ['empresas.id'], ),
    sa.ForeignKeyConstraint(['factura_id'], ['facturas.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('pagos')
    op.drop_table('notas_debito')
    op.drop_table('notas_credito')
    op.drop_table('detalles_factura')
    op.drop_table('detalles_cotizacion')
    op.drop_table('kardex')
    op.drop_table('facturas')
    op.drop_table('cotizaciones')
    op.drop_index(op.f('ix_usuarios_email'), table_name='usuarios')
    op.drop_table('usuarios')
    op.drop_table('proveedores')
    op.drop_table('productos')
    op.drop_table('plantillas_factura')
    op.drop_table('clientes')
    op.drop_table('empresas')
    # ### end Alembic commands ###
